import Foundation

/// A regenerable build/dependency directory found inside a project — the kind of
/// thing the single-level recipe globber can't reach (`~/**/node_modules`). It's
/// attributed to its project so the user always sees WHICH project it belongs to
/// before reclaiming. Reversible: everything here rebuilds from source or a
/// package manager.
public struct RepoArtifact: Sendable, Identifiable, Codable {
    public var id: String { path }
    public let path: String        // the artifact dir, e.g. …/myapp/node_modules
    public let project: String     // the owning project folder's name
    public let kind: String        // "node_modules", ".next", "target", …
    public let bytes: Int64
    public let lastModified: Date?

    public init(path: String, project: String, kind: String, bytes: Int64, lastModified: Date?) {
        self.path = path; self.project = project; self.kind = kind
        self.bytes = bytes; self.lastModified = lastModified
    }

    /// Plain-language "what rebuilds this" note for the finding.
    public var rebuildNote: String {
        switch kind {
        case "node_modules": "Installed npm/yarn/pnpm packages — rebuilt by `npm install` (needs network)."
        case ".next":        "Next.js build cache — rebuilt on the next `next dev`/`build`."
        case "dist", "build", "out": "Compiled output — regenerated by your next build."
        case "target":       "Rust/Java build output — regenerated by `cargo build` / your build tool."
        case ".gradle":      "Gradle build cache — re-downloaded/rebuilt on next Gradle run."
        case "Pods":         "CocoaPods dependencies — restored by `pod install`."
        case "__pycache__":  "Python bytecode cache — regenerated automatically when code runs."
        case ".venv", "venv": "Python virtual environment — recreated by `python -m venv` + install."
        case "vendor":       "Dependency vendor directory — restored by your package manager."
        default:              "Regenerated by your build/package tooling."
        }
    }
}

/// Bounded, repo-aware walk of the user's home for large regenerable build
/// artifacts. Prunes aggressively (skips ~/Library, hidden trees, and never
/// recurses INTO a matched artifact) so it stays fast, and only reports an
/// artifact when its parent looks like a real project. Read-only.
public struct RepoScanner: Sendable {
    public struct Config: Sendable {
        public var maxDepth = 7
        public var minBytes: Int64 = 50 * 1024 * 1024     // 50 MB — skip noise
        public var maxArtifacts = 200
        public init() {}
    }

    /// Directory names we treat as regenerable build artifacts.
    static let artifactKinds: Set<String> = [
        "node_modules", ".next", "dist", "build", "out",
        "target", ".gradle", "Pods", "__pycache__", ".venv", "venv", "vendor",
    ]

    /// Files that mark a folder as a real project, so we don't flag a random
    /// "build" or "dist" folder that isn't build output.
    static let projectMarkers: Set<String> = [
        "package.json", "Cargo.toml", "go.mod", "pom.xml", "build.gradle",
        "build.gradle.kts", "Podfile", "pyproject.toml", "requirements.txt",
        "setup.py", "Gemfile", "composer.json", ".git", "tsconfig.json",
    ]

    /// Top-level home entries we never descend into (system/library/personal
    /// media that can't contain source projects worth pruning).
    static let skipDirs: Set<String> = [
        "Library", "Applications", ".Trash", "Pictures", "Music", "Movies",
        "Photos Library.photoslibrary",
    ]

    public var config: Config
    public init(config: Config = Config()) { self.config = config }

    public func scan(homeOverride: String? = nil) -> [RepoArtifact] {
        let home = homeOverride ?? NSHomeDirectory()
        var out: [RepoArtifact] = []
        walk(URL(fileURLWithPath: home), depth: 0, home: home, out: &out)
        return out.sorted { $0.bytes > $1.bytes }
    }

    private func walk(_ dir: URL, depth: Int, home: String, out: inout [RepoArtifact]) {
        guard depth <= config.maxDepth, out.count < config.maxArtifacts else { return }
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey],
            options: []) else { return }

        // Which subdirectories are candidates, and does this dir look like a project?
        var subdirs: [URL] = []
        var names = Set<String>()
        for e in entries {
            let v = try? e.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey])
            names.insert(e.lastPathComponent)
            if v?.isSymbolicLink == true { continue }          // never follow symlinks
            if v?.isDirectory == true { subdirs.append(e) }
        }
        let isProject = !names.isDisjoint(with: Self.projectMarkers)

        for sub in subdirs {
            let name = sub.lastPathComponent
            // Top-level prunes (only meaningful directly under home).
            if depth == 0 && Self.skipDirs.contains(name) { continue }
            // Skip hidden trees except the specific dot-artifacts we care about.
            if name.hasPrefix(".") && !Self.artifactKinds.contains(name) { continue }

            if Self.artifactKinds.contains(name) && isProject {
                let m = SizeMeasurement.measure(sub.path)
                if m.allocatedBytes >= config.minBytes {
                    out.append(RepoArtifact(
                        path: sub.path, project: dir.lastPathComponent, kind: name,
                        bytes: m.allocatedBytes, lastModified: m.lastModified))
                }
                // Never recurse INTO a matched artifact.
                continue
            }
            walk(sub, depth: depth + 1, home: home, out: &out)
        }
    }
}
